/*
 * es310_configs.h  --  ES310 ALSA Soc Audio driver
 *
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * The download image for the ES310 will be requested as
 * 'es310_anc.bin' by default (overridable via platform data) at
 * runtime and is expected to be in flat binary format.  This is
 * generated by Wolfson configuration tools and includes
 * system-specific callibration information.  If supplied as a
 * sequence of ASCII-encoded hexidecimal bytes this can be converted
 * into a flat binary with a command such as this on the command line:
 *
 * perl -e 'while (<>) { s/[\r\n]+
 *                 < file  > es310_anc.bin
 */
/***********************************************************************/
/* Modified by                                                         */
/* (C) NEC CASIO Mobile Communications, Ltd. 2013                      */
/***********************************************************************/
#if !defined(__LINUX_SND_ES310_CONFIG_H)
#define __LINUX_SND_ES310_CONFIG_H

#define ES310_REQUEST_FIRMWARE

#define VER(MAJ,MIN)    ((MAJ<0xF)|(MIN))


































static unsigned short ES310_MODE_OFF[]={
0x801C,0x0000,
0x800C,0x1002,0x800D,0x0000,
0x800C,0x1102,0x800D,0x0000,
};
#endif
