#/***********************************************************************/
#/* Modified by                                                         */
#/* (C) NEC CASIO Mobile Communications, Ltd. 2013                      */
#/***********************************************************************/


ccflags-y := -I../
obj-$(CONFIG_FEATURE_DVE021_MHL) += mhl_8334.o
obj-$(CONFIG_FEATURE_DVE021_MHL) += mhl_i2c_utils.o


clean:
	rm *.o .*cmd
