#/***********************************************************************/
#/* Modified by                                                         */
#/* (C) NEC CASIO Mobile Communications, Ltd. 2013                      */
#/***********************************************************************/

obj-$(CONFIG_KEY_DIAG_W) += key_diag_wrapper.o
obj-$(CONFIG_TOUCHPANEL_DIAG_W) += touchpanel_diag_wrapper.o
